import { ITicketItem } from "./pages/Infoticket";

export const ticketsContent: ITicketItem[] = [
  {
    imgPath: "LK2.jpg",
    title: "Dino Show",
    date: "Sabtu, Minggu dan Hari Libur",
    price: "15.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "atv.jpg",
    title: "ATV",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "lowrope.jpg",
    title: "Low Rope",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "berkuda.jpg",
    title: "Berkuda",
    date: "Setiap Hari",
    price: "50.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "jltshort.png",
    title: "Jeep Lawu Tour (Short Trip)",
    date: "Setiap Hari",
    price: "350.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "jltmedium.jpg",
    title: "Jeep Lawu Tour (Medium Trip)",
    date: "Setiap Hari",
    price: "450.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "jltlong.jpg",
    title: "Jeep Lawu Tour (Long Trip)",
    date: "Setiap Hari",
    price: "550.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "basketgoyang.jpg",
    title: "Basket Goyang",
    date: "Setiap Hari",
    price: "10.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "logo.png",
    title: "Pukul Buaya",
    date: "Setiap Hari",
    price: "10.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "logo.png",
    title: "Dart Board",
    date: "Setiap Hari",
    price: "10.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "archery.jpg",
    title: "Archery",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "paintball.jpg",
    title: "Paintball (Shoting Target)",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "paintballwg.jpg",
    title: "Paintball (War Game)",
    date: "Setiap Hari",
    price: "70.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "agpendek.jpg",
    title: "Airsoft Gun (Laras Pendek)",
    date: "Setiap Hari",
    price: "45.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "agpanjang.jpg",
    title: "Airsoft Gun (Laras Panjang)",
    date: "Setiap Hari",
    price: "55.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "agwar.jpg",
    title: "Airsoft Gun (War Game)",
    date: "Setiap Hari",
    price: "100.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "minijeep.jpg",
    title: "Mini Jeep",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "logo.png",
    title: "Mini Trail",
    date: "Setiap Hari",
    price: "30.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "logo.png",
    title: "Play Ground",
    date: "Setiap Hari",
    price: "25.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "logo.png",
    title: "Rolling Ball",
    date: "Setiap Hari",
    price: "15.000",
    link: "",
    desc: "",
  },
  {
    imgPath: "dinoride.jpeg",
    title: "Dino Ride",
    date: "Setiap Hari",
    price: "20.000",
    link: "",
    desc: "",
  },
];
